name: Deploy

on:
  release:
    types: [published]

env:
  NugetKey: ${{ secrets.NUGET_APIKEY }}

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow
      - uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: |
            6.0
            7.0
            8.0
      - name: Deploy project
        uses: cake-build/cake-action@v1.4.1
        with:
          script-path: build.cake
          target: Deploy
          arguments: |
            packageversion: ${{ github.ref }}